### ISSUE TITLE
[GetX] dynamic url error, NoSuchMethodError: method not found: 'ga2F' on null

### ISSUE THREAD

**Issue by KKimj** [KKimj/emo-Book#6]
```
NoSuchMethodError: method not found: 'ga2F' on null
js_primitives.dart:47     at BF.Ia (http://localhost:53486/main.dart.js:56016:5)
js_primitives.dart:47     at rp.Jm (http://localhost:53486/main.dart.js:55525:40)
js_primitives.dart:47     at Object.eval (eval at abu (http://localhost:53486/main.dart.js:3410:8), <anonymous>:3:36)
js_primitives.dart:47     at xz.Td (http://localhost:53486/main.dart.js:47209:21)
js_primitives.dart:47     at Object.eval (eval at abu (http://localhost:53486/main.dart.js:3410:8), <anonymous>:3:36)
js_primitives.dart:47     at fN.mn (http://localhost:53486/main.dart.js:51666:16)
js_primitives.dart:47     at E5.akj (http://localhost:53486/main.dart.js:15403:10)
js_primitives.dart:47     at tr.a_m (http://localhost:53486/main.dart.js:51395:33)
js_primitives.dart:47     at fN.jC (http://localhost:53486/main.dart.js:51511:16)
js_primitives.dart:47     at fN.aK (http://localhost:53486/main.dart.js:51892:9)
js_primitives.dart:47 Another exception was thrown: Instance of 'minified:dD<void>'
```

**Comment by KKimj** [comment]
```dart
      GetPage(name: '/book/', page: () => BookPage()),
      GetPage(name: '/book/:isbn', page: () => BookPage()),
```

Must be ```'/{view}/'``` as default

```dart
class MainScaffold extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var _getPages = <GetPage>[
      GetPage(name: '/', page: () => HomePage()),
      GetPage(name: '/book/', page: () => BookPage()),
      GetPage(name: '/book/:isbn', page: () => BookPage()),
      GetPage(name: '/debug', page: () => DebugPage()),
    ];

    return GetMaterialApp(
      title: 'emo-book :: 감정기반 도서 추천 서비스',
      home: HomePage(),
      theme: EmoLightTheme,
      getPages: _getPages,
      initialBinding: AppBinding(),
    );
  }
}```
